### PR TITLE
Fix GriefPrevention max claimblocks calculation.

### LINKED ISSUE #67: When trading GriefPrevention territory cubes, you can only trade part of the territory cubes
When I'm trading to other players, the territory cubes can only be traded for 4. But I actually have over 200. I don't know if it's the plugin

Plugin version: 3.79
Server side version: 1.16.4
Server type: Tuinity
GriefPrevention plugin version: 16.16.0

### LINKED ISSUE #82: griefprevention blocks 0 when trading when someone
Hello

when you try to trade claimblocks with someone it says you have 0 claim blocks. even if you have a lot. (yes we use the correct plugin for claim blocks)

### PR DESCRIPTION
**Pull request by RezzedUp**
This patch allows players to trade their accrued claimblocks once again, instead of just their bonus claimblocks. It also fixes several issues with building the plugin (by updating/removing improperly-defined and unused dependencies).

- Fixes #67 
- Fixes #82

### CODE REVIEW

**Comment by Trophonix** [comment]
Have you tested with this? When I used accrued claimblocks before, I believe someone reported the issue that GriefPrevention plugin would automatically grant players the default claim block amount when they traded down to 0 claim blocks, effectively making duplication of claim blocks possible.

**Comment by RezzedUp** [comment]
Yes, I did test it. That shouldn't be an issue because it's modifying bonus claimblocks value, not accrued claimblocks.

**Comment by Trophonix** [comment]
What happens if a user has 1000 bonus claim blocks, 1200 total, and they trade away all 1200? Their bonus claim blocks would be set to negative 200?

**Comment by RezzedUp** [comment]
> Looking at the GriefPrevention code, it looks like this would still trigger the plugin to give them new claim blocks.

Not quite sure where you're seeing that because it only adjusts [**accrued** claimblocks](https://github.com/TechFortress/GriefPrevention/blob/6debf368c9823c01fe747d70d5c1845024d86fa1/src/main/java/me/ryanhamshire/GriefPrevention/PlayerData.java#L220-L224) if they're less than the config's default value. Bonus claimblocks are a separate value and aren't affected by that.

GriefPrevention calculates remaining claimblocks by adding accrued claimblocks with bonus claimblocks, and since bonus claimblocks can be negative (and aren't reset to a minimum amount), subtracting traded claimblocks from the bonus amount works as intended. Here are a few screenshots of a trade in action:

**Comment by Trophonix** [comment]
I was mistaken when looking at the GriefPrevention code, I was seeing a section which restored claim blocks to a player when their total claimed land exceeded their total claim blocks.

**Pull request merged**
